[package]
name = "hive-ai"
version = "0.1.0"
edition = "2021"
authors = ["HiveTechs Collective <team@hivetechs.com>"]
description = "AI-powered codebase intelligence platform with multi-model consensus"
repository = "https://github.com/hivetechs/hive"
license = "Proprietary"
keywords = ["ai", "code-intelligence", "development-tools", "consensus", "mcp"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ["full"] }
futures = "0.3"

# Web framework
axum = { version = "0.7", features = ["ws", "macros"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "compression-br", "trace"] }
hyper = "1.1"

# Parsing and code analysis
tree-sitter = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-typescript = "0.20"
tree-sitter-python = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-go = "0.20"
tree-sitter-java = "0.20"
tree-sitter-cpp = "0.20"

# Database and search
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio", "migrate"] }
tantivy = "0.21"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rkyv = { version = "0.7", features = ["validation"] }
toml = "0.8"

# Concurrency and parallelism
crossbeam = "0.8"
dashmap = "5.5"
rayon = "1.8"
parking_lot = "0.12"
arc-swap = "1.6"

# HTTP client
reqwest = { version = "0.11", features = ["stream", "json"] }
eventsource-stream = "0.2"

# CLI
clap = { version = "4.4", features = ["derive", "env"] }
dialoguer = "0.11"
indicatif = "0.17"
console = "0.15"
termion = "3.0"
colored = "2.1"

# TUI (optional feature)
ratatui = { version = "0.25", optional = true }
crossterm = { version = "0.27", optional = true }
tui-textarea = { version = "0.4", optional = true }
syntect = { version = "5.1", optional = true }
atty = "0.2"
chrono-tz = "0.8"

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Utilities
once_cell = "1.19"
regex = "1.10"
glob = "0.3"
walkdir = "2.4"
notify = "6.1"
memmap2 = "0.9"
base64 = "0.21"
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
shellexpand = "3.1"
md5 = "0.7"

# Security
ring = "0.17"
argon2 = "0.5"
jsonwebtoken = "9.2"

# Performance monitoring
metrics = "0.22"
metrics-exporter-prometheus = "0.13"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"
mockall = "0.12"
insta = { version = "1.34", features = ["yaml"] }
test-case = "3.3"
tempfile = "3.8"
wiremock = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1

[features]
default = ["tui"]
tui = ["ratatui", "crossterm", "tui-textarea", "syntect"]
interactive = ["ratatui", "crossterm"]  # Claude Code-style interactive mode
minimal = []  # CLI-only build without TUI

[[bin]]
name = "hive"
path = "src/main.rs"

[lib]
name = "hive_ai"
path = "src/lib.rs"

# Global installation configuration
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"

# Cross-platform build targets for global distribution
[package.metadata.dist]
targets = [
    "x86_64-apple-darwin",      # macOS Intel
    "aarch64-apple-darwin",     # macOS Apple Silicon
    "x86_64-unknown-linux-gnu", # Linux x64
    "aarch64-unknown-linux-gnu",# Linux ARM64
    "x86_64-pc-windows-msvc",   # Windows x64
]

# Auto-update and global installation features
cargo-dist-version = "0.8.0"
ci = ["github"]
installers = ["shell", "powershell", "npm", "homebrew", "msi"]
tap = "hivetechs/homebrew-tap"
publish-jobs = ["homebrew"]

# Benchmarks will be added later
# [[bench]]
# name = "parsing"
# harness = false

# [[bench]]
# name = "consensus"
# harness = false