# Fish completion for Hive AI
# Generated by Hive AI Shell Integration

# Remove file completion by default
complete -c hive -f

# Global options
complete -c hive -s h -l help -d "Show help information"
complete -c hive -s V -l version -d "Show version information"
complete -c hive -s v -l verbose -d "Increase verbosity"
complete -c hive -s q -l quiet -d "Suppress output"
complete -c hive -l format -d "Output format" -x -a "text json yaml markdown table"
complete -c hive -l no-color -d "Disable colored output"

# Main commands
complete -c hive -n "__fish_use_subcommand" -a "analyze" -d "🔍 Analyze and understand any repository"
complete -c hive -n "__fish_use_subcommand" -a "ask" -d "🤖 Ask the AI consensus a question"
complete -c hive -n "__fish_use_subcommand" -a "consensus" -d "🎯 Run 4-stage consensus analysis"
complete -c hive -n "__fish_use_subcommand" -a "plan" -d "📋 Enter planning mode for complex tasks"
complete -c hive -n "__fish_use_subcommand" -a "execute" -d "⚡ Execute a previously created plan"
complete -c hive -n "__fish_use_subcommand" -a "improve" -d "✨ Apply AI-suggested improvements"
complete -c hive -n "__fish_use_subcommand" -a "search" -d "🔎 Search for symbols in codebase"
complete -c hive -n "__fish_use_subcommand" -a "memory" -d "🧠 Manage long-term memory"
complete -c hive -n "__fish_use_subcommand" -a "analytics" -d "📊 Generate analytics reports"
complete -c hive -n "__fish_use_subcommand" -a "config" -d "⚙️ Manage configuration settings"
complete -c hive -n "__fish_use_subcommand" -a "trust" -d "🔒 Manage directory trust settings"
complete -c hive -n "__fish_use_subcommand" -a "hooks" -d "🪝 Manage enterprise hooks"
complete -c hive -n "__fish_use_subcommand" -a "shell" -d "🔧 Manage shell integration"
complete -c hive -n "__fish_use_subcommand" -a "status" -d "📈 Show system status"
complete -c hive -n "__fish_use_subcommand" -a "completion" -d "🐚 Generate shell completions"
complete -c hive -n "__fish_use_subcommand" -a "self-update" -d "🔄 Self-update Hive AI binary"

# Analyze command options
complete -c hive -n "__fish_seen_subcommand_from analyze" -l depth -d "Analysis depth" -x -a "quick standard comprehensive"
complete -c hive -n "__fish_seen_subcommand_from analyze" -l focus -d "Focus areas" -x -a "architecture quality security performance"
complete -c hive -n "__fish_seen_subcommand_from analyze" -l output -d "Save to file" -r

# Ask command options
complete -c hive -n "__fish_seen_subcommand_from ask" -l profile -d "Consensus profile" -x -a "speed balanced cost elite"
complete -c hive -n "__fish_seen_subcommand_from ask" -l plan -d "Enable planning mode"
complete -c hive -n "__fish_seen_subcommand_from ask" -l context -d "Include context" -r

# Shell subcommands
complete -c hive -n "__fish_seen_subcommand_from shell" -a "install" -d "📦 Install shell integration"
complete -c hive -n "__fish_seen_subcommand_from shell" -a "setup" -d "⚙️ Setup PATH and environment"
complete -c hive -n "__fish_seen_subcommand_from shell" -a "status" -d "📊 Show integration status"
complete -c hive -n "__fish_seen_subcommand_from shell" -a "completions" -d "🐚 Generate completion files"
complete -c hive -n "__fish_seen_subcommand_from shell" -a "uninstall" -d "🗑️ Remove shell integration"

# Completion command options
complete -c hive -n "__fish_seen_subcommand_from completion" -a "bash zsh fish powershell" -d "Shell type"

# Professional abbreviations
abbr -a ha 'hive analyze'
abbr -a hq 'hive ask'
abbr -a hp 'hive plan'
abbr -a hs 'hive search'
abbr -a hst 'hive status'