# Bash completion for Hive AI
# Generated by Hive AI Shell Integration
# Place this file in /etc/bash_completion.d/ or ~/.bash_completion.d/

_hive_completion() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    # Main commands
    opts="analyze ask consensus plan execute improve search memory analytics config trust hooks shell status completion self-update"
    
    case "${prev}" in
        hive)
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            ;;
        shell)
            COMPREPLY=( $(compgen -W "install setup status completions uninstall" -- ${cur}) )
            return 0
            ;;
        --profile)
            COMPREPLY=( $(compgen -W "speed balanced cost elite" -- ${cur}) )
            return 0
            ;;
        --format)
            COMPREPLY=( $(compgen -W "text json yaml markdown table" -- ${cur}) )
            return 0
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- ${cur}) )
            return 0
            ;;
    esac
    
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _hive_completion hive

# Professional aliases
alias ha='hive analyze'
alias hq='hive ask'
alias hp='hive plan'
alias hs='hive search'
alias hst='hive status'