name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  backend-rust:
    name: Backend (Rust)
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI disabled; backend checks handled locally"

  electron-unit:
    name: Electron Unit & Lint
    runs-on: macos-latest
    needs: backend-rust
    steps:
      - run: echo "CI disabled; electron checks handled locally"

  ui-smoke:
    name: UI Smoke (macOS)
    runs-on: macos-latest
    needs: [electron-unit]
    if: false
    steps:
      - run: echo "skipped"

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [backend-rust, electron-unit, ui-smoke]
    if: always()
    steps:
      - run: echo "CI/CD disabled; use local build:complete + release:local" >> "$GITHUB_STEP_SUMMARY"
