name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  rust:
    name: Backend (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk-3-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev libxdo-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Lint with Clippy
        run: cargo clippy --all-targets --bin hive-backend-server-enhanced

      - name: Run tests
        run: cargo test --bin hive-backend-server-enhanced

  electron-unit:
    name: Electron Unit & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Python model service
        run: |
          mkdir -p electron-poc/resources/python-runtime/models
          cp python/model_service.py electron-poc/resources/python-runtime/models/model_service.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: electron-poc/package-lock.json

      - name: Install dependencies
        working-directory: electron-poc
        run: npm ci

      - name: Type checks
        working-directory: electron-poc
        run: npm run verify:modules && npm run verify:types

  ui-smoke:
    name: UI Smoke (macOS)
    runs-on: macos-latest
    needs: [rust, electron-unit]
    if: >-
      ${{ github.event_name == 'push' ||
          (github.event_name == 'pull_request' &&
           contains(github.event.pull_request.labels.*.name, 'ui-smoke')) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: electron-poc/package-lock.json

      - name: Install dependencies
        working-directory: electron-poc
        run: npm ci

      - name: Install macOS tooling
        run: |
          if ! command -v ttyd >/dev/null; then
            brew install ttyd
          fi

      - name: Install Playwright browser
        working-directory: electron-poc
        run: npx playwright install chromium

      - name: Build packaged app and run smoke tests
        working-directory: electron-poc
        env:
          PLAYWRIGHT_E2E: '1'
          PLAYWRIGHT_REMOTE_DEBUG_PORT: '61323'
          PLAYWRIGHT_RUN_TESTS: '1'
        run: npm run build:complete

      - name: Upload packaged artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-${{ github.run_number }}
          path: |
            electron-poc/out/make/*.dmg
            electron-poc/out/make/*.zip
          if-no-files-found: warn

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [rust, electron-unit, ui-smoke]
    if: always()
    steps:
      - name: Write summary
        run: |
          rust="${{ needs.rust.result }}"
          fe="${{ needs.electron-unit.result }}"
          ui="${{ needs.ui-smoke.result || 'skipped' }}"

          function icon() {
            case "$1" in
              success) echo "✅" ;;
              skipped) echo "⚪" ;;
              *) echo "❌" ;;
            esac
          }

          {
            echo "## CI results"
            echo ""
            echo "- $(icon "$rust") Rust backend (${rust})"
            echo "- $(icon "$fe") Electron unit & lint (${fe})"
            echo "- $(icon "$ui") UI smoke (${ui})"
          } >> "$GITHUB_STEP_SUMMARY"
