name: CI (disabled)

on:
  # CI disabled to avoid minutes; manual-only if explicitly dispatched
  workflow_dispatch:

jobs:
  noop:
    name: CI Disabled
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI/CD disabled; use local build:complete + release:local"
